# Cloudflare account ID
name = "cloudflare-worker-template-prod"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat", "nodejs_als"]
pages_build_output_dir = ".vercel/output/static"

# D1 database binding 
[[d1_databases]]
binding = "DB"
database_name = "cloudflare-worker-template-prod"
database_id = "6e91e757-b85e-4d43-a2c4-6c503e0cc9c2"
migrations_dir = "migrations"

# R2 bucket binding 
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cloudflare-worker-template-prod"

# KV namespace
[[kv_namespaces]]
binding = "KV"
id = "52ca46605f5d4d0698f4d0bceac713a1"

# Environment variables
[vars]
ENVIRONMENT = "production"
ANALYTICS_SINK = "engine"

# Analytics Engine dataset binding
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "prod_analytics_dataset"  # Use underscore instead of hyphen
