blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://github.com/your-org/cloudflare-worker-template/security/policy
    about: Please follow the security policy for responsibly disclosing vulnerabilities.
